// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '..',
    appId: '1:180447179627:web:7acb03ce408e62699d522e',
    messagingSenderId: '180447179627',
    projectId: 'codepac-d88e3',
    authDomain: 'codepac-d88e3.firebaseapp.com',
    storageBucket: 'codepac-d88e3.firebasestorage.app',
    measurementId: 'G-BWCJGF99D6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '..',
    appId: '1:180447179627:android:99b06676df88d2279d522e',
    messagingSenderId: '180447179627',
    projectId: 'codepac-d88e3',
    storageBucket: 'codepac-d88e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '..',
    appId: '1:180447179627:ios:bb5fe2c3aa5fe5d69d522e',
    messagingSenderId: '180447179627',
    projectId: 'codepac-d88e3',
    storageBucket: 'codepac-d88e3.firebasestorage.app',
    iosBundleId: 'com.codepac.eduzapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '..',
    appId: '1:180447179627:ios:bb5fe2c3aa5fe5d69d522e',
    messagingSenderId: '180447179627',
    projectId: 'codepac-d88e3',
    storageBucket: 'codepac-d88e3.firebasestorage.app',
    iosBundleId: 'com.codepac.eduzapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '..',
    appId: '1:180447179627:web:41b5e020aeee2b379d522e',
    messagingSenderId: '180447179627',
    projectId: 'codepac-d88e3',
    authDomain: 'codepac-d88e3.firebaseapp.com',
    storageBucket: 'codepac-d88e3.firebasestorage.app',
    measurementId: 'G-25JB7WKCVQ',
  );
}
